### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zirnc**
cyberos -> cutefishos

### CODE REVIEW

**Comment by zirnc** [comment]
hi @probonopd , can you merge this PR?

**Comment by kettle-7** [comment]
Isn't the CuteFish dock another fork of the Cyber dock? helloSystem's dock is not based on the CuteFish dock, it's based on cyber-dock which CuteFish just happens to also base their dock off.

**Comment by zirnc** [comment]
Cyber is dead :) The founder of Cyber now created Cutefish

**Comment by probonopd** [comment]
Thank you @ChungZH

**Pull request merged**
